AWSTemplateFormatVersion: '2010-09-09'
Description: ALB + Target Group + Security Groups and Listener

Parameters:
  StackNamePrefix:
    Type: String
    Description: Prefix för resursnamn (t.ex. wp-cf)
  VpcId:
    Type: String
    Description: VPC där ALB ska ligga
  PublicSubnetIds:
    Type: CommaDelimitedList
    Description: Två (eller fler) publika subnät i olika AZ för ALB

Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${StackNamePrefix}-alb'
      Scheme: internet-facing
      Type: application
      Subnets: !Ref PublicSubnetIds
      SecurityGroups:
        - !Ref AlbSecurityGroup
      IpAddressType: ipv4
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: "false"    # development phase: easier to tear down the stack
          
  AlbSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ALB SG - allow HTTP from Internet
      VpcId: !Ref VpcId
      SecurityGroupIngress: # In-traffic to ALB, public Internet
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress: # Out from ALB, IpProtocol: -1 means all protocol, all ports
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-alb-sg'
  HttpListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${StackNamePrefix}-tg'
      VpcId: !Ref VpcId
      Protocol: HTTP
      Port: 80
      TargetType: instance
      HealthCheckProtocol: HTTP
      HealthCheckPort: traffic-port
      HealthCheckPath: / # could also become /health.html
      Matcher:
        HttpCode: '200-399'

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
    Description: ARN för Target Group
  AlbArn:
    Value: !Ref ALB
    Description: ARN för Application Load Balancer
  AlbDNS:
    Value: !GetAtt ALB.DNSName
    Description: Publik DNS för ALB
  ListenerArn:
    Value: !Ref HttpListener
    Description: ARN för HTTP-listener (port 80 → Target Group)
  AlbSecurityGroupId:
    Value: !Ref AlbSecurityGroup
    Description: Security Group ID för ALB