AWSTemplateFormatVersion: '2010-09-09'
Description: MariaDB on EC2 (minimal step, IAM role + one instance in private DB subnet)

Parameters:
  StackNamePrefix: { Type: String }
  VpcId:           { Type: String }
  PrivateDbSubnetIds:
    Type: CommaDelimitedList
    Description: Two private DB subnets (we will place the instance in the first)
  DbSecurityGroupId:
    Type: String
    Description: SG-ID from 40-db-sg.yaml
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t3.small]
    Description: EC2 type for MariaDB
  AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: Amazon Linux 2023
  DbName: { Type: String }
  DbUser:
    Type: String
    Default: wp_user
  DbPassword:
    Type: String
    NoEcho: true
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: { Service: ec2.amazonaws.com }
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-db-role'

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [ !Ref InstanceRole ]

  DbInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      SubnetId: !Select [0, !Ref PrivateDbSubnetIds]
      SecurityGroupIds: [ !Ref DbSecurityGroupId ]
      KeyName:        !Ref KeyPairName
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 20
            VolumeType: gp3
            DeleteOnTermination: true
      MetadataOptions: { HttpTokens: required }
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-db-ec2'
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          set -eux

          dnf -y update
          dnf -y install mariadb105-server

          systemctl enable --now mariadb

          # Lyssna på privat IP (annars bara 127.0.0.1)
          cat >/etc/my.cnf.d/bind.cnf <<'EOF'
          [mysqld]
          bind-address=0.0.0.0
          EOF
          systemctl restart mariadb

          # Skapa DB + app-user (root via unix_socket)
          mysql --protocol=socket -uroot <<SQL
          CREATE DATABASE IF NOT EXISTS \`${DbName}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
          CREATE OR REPLACE USER '${DbUser}'@'%' IDENTIFIED BY '${DbPassword}';
          GRANT ALL PRIVILEGES ON `${DbName}`.* TO '${DbUser}'@'%';
          FLUSH PRIVILEGES;
          SQL

          echo "MariaDB ready on $(hostname -f)" > /etc/motd

Outputs:
  DbInstanceId:
    Value: !Ref DbInstance
    Description: EC2 instance ID for MariaDB
  DbPrivateIp:
    Value: !GetAtt DbInstance.PrivateIp
    Description: Private IP of the DB instance
  DbAz:
    Value: !GetAtt DbInstance.AvailabilityZone
    Description: AZ of the DB instance