AWSTemplateFormatVersion: '2010-09-09'
Description: WordPress app tier - stegvis bygge (börjar med parametrar)

Parameters:
  StackNamePrefix:
    Type: String
  VpcId:
    Type: String
  AlbSecurityGroupId:
    Type: String
    Description: SG-ID för ALB (källa för HTTP-ingress)
  InstanceType:
    Type: String
    Default: t3.micro
    AllowedValues: [t3.micro, t3.small]
    Description: EC2-instancs-typ för app-lagret
  AmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
    Description: Senaste Amazon Linux 2023 AMI via SSM
  PrivateAppSubnetIds:
    Type: CommaDelimitedList
    Description: Privata app-subnät (minst två AZ)
  TargetGroupArn:
    Type: String
    Description: TargetGroup från 20-alb.yaml
  FileSystemId:
    Type: String
    Description: EFS FileSystemId att montera på instanserna

Resources:
  AppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: App SG - allow HTTP only from ALB-SG
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref AlbSecurityGroupId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-app-sg'
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${StackNamePrefix}-lt'
      LaunchTemplateData:
        ImageId: !Ref AmiId
        InstanceType: !Ref InstanceType
        SecurityGroupIds: [ !Ref AppSecurityGroup ]
        MetadataOptions: { HttpTokens: required }
        TagSpecifications:
          - ResourceType: instance
            Tags: [{ Key: Name, Value: !Sub '${StackNamePrefix}-app' }]
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -eux
            mkdir -p /var/www/html
            echo "<h1>ASG OK (utan EFS)</h1><p>Server: $(hostname -f)</p>" > /var/www/html/index.html
            nohup python3 -m http.server 80 --directory /var/www/html >/var/log/http.server.log 2>&1 &
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: false
      AutoScalingRollingUpdate:
        MinInstancesInService: '0'
        MaxBatchSize: '1'
        PauseTime: PT2M
    Properties:
      VPCZoneIdentifier: !Ref PrivateAppSubnetIds
      MinSize: '1'
      MaxSize: '2'
      DesiredCapacity: '1'
      TargetGroupARNs: [ !Ref TargetGroupArn ]
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      HealthCheckType: ELB
      HealthCheckGracePeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${StackNamePrefix}-asg'
          PropagateAtLaunch: true

Outputs:
  AppSecurityGroupId:
    Value: !Ref AppSecurityGroup
    Description: SG-ID för WordPress-instanser