AWSTemplateFormatVersion: '2010-09-09'
Description: Bastion/Deploy VM (scaffold)

Parameters:
  StackNamePrefix: { Type: String }
  VpcId: { Type: String }
  PublicSubnetId: { Type: String }
  KeyPairName: { Type: AWS::EC2::KeyPair::KeyName }
  AllowedSshCidr: { Type: String }
  EfsFileSystemId: { Type: String }
  DBEndpoint: { Type: String }
  DBName: { Type: String }
  DBUsername: { Type: String }
  DBPassword: { Type: String, NoEcho: true }

Resources: {}
Outputs: {}