AWSTemplateFormatVersion: '2010-09-09'
Description: Root stack for WordPress infra using nested stacks

Parameters:
  StackNamePrefix:
    Type: String
    Default: wp-cf
    Description: Prefix for naming resources
  TemplateBucket:
    Type: String
    Description: S3 bucket name where child templates are stored (wordpress-iac-<account-id>-<region>)
  TemplatePrefix:
    Type: String
    Default: wordpress-iac/templates/
    Description: Key prefix inside the S3 bucket (directory path)
  VpcCidr:
    Type: String
    Default: 10.20.0.0/16
  PublicSubnetCidrs:
    Type: String
    Default: 10.20.0.0/24,10.20.1.0/24
  PrivateAppSubnetCidrs:
    Type: String
    Default: 10.20.20.0/24,10.20.21.0/24
  PrivateDbSubnetCidrs:
    Type: String
    Default: 10.20.20.0/24,10.20.21.0/24

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}00-network.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        VpcCidr: !Ref VpcCidr
        PublicSubnetCidrs: !Ref PublicSubnetCidrs
        PrivateAppSubnetCidrs: !Ref PrivateAppSubnetCidrs
        PrivateDbSubnetCidrs: !Ref PrivateDbSubnetCidrs
  AlbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}20-alb.yaml'
      Parameters:
        StackNamePrefix: !Ref StackNamePrefix
        VpcId:            !GetAtt NetworkStack.Outputs.VpcId
        PublicSubnetIds:  !GetAtt NetworkStack.Outputs.PublicSubnetIds
  AsgStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AlbStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}50-asg-wordpress.yaml'
      Parameters:
        StackNamePrefix:     !Ref StackNamePrefix
        VpcId:               !GetAtt NetworkStack.Outputs.VpcId
        AlbSecurityGroupId:  !GetAtt AlbStack.Outputs.AlbSecurityGroupId
        PrivateAppSubnetIds: !GetAtt NetworkStack.Outputs.PrivateAppSubnetIds
        TargetGroupArn:      !GetAtt AlbStack.Outputs.TargetGroupArn
        FileSystemId:        !GetAtt EfsStack.Outputs.FileSystemId
  EfsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NetworkStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}30-efs.yaml'
      Parameters:
        StackNamePrefix:     !Ref StackNamePrefix
        VpcId:               !GetAtt NetworkStack.Outputs.VpcId
        PrivateAppSubnetIds: !GetAtt NetworkStack.Outputs.PrivateAppSubnetIds
        PrivateAppSubnetCidrs:  !Ref PrivateAppSubnetCidrs
  DbStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AsgStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}40-db-sg.yaml'
      Parameters:
        StackNamePrefix:      !Ref StackNamePrefix
        VpcId:                !GetAtt NetworkStack.Outputs.VpcId
        AppSecurityGroupId:   !GetAtt AsgStack.Outputs.AppSecurityGroupId
  DbEc2Stack:
    Type: AWS::CloudFormation::Stack
    DependsOn: DbStack
    Properties:
      TemplateURL: !Sub 'https://s3.${AWS::Region}.amazonaws.com/${TemplateBucket}/${TemplatePrefix}45-db-mariadb-ec2.yaml'
      Parameters:
        StackNamePrefix:      !Ref StackNamePrefix
        VpcId:                !GetAtt NetworkStack.Outputs.VpcId
        PrivateDbSubnetIds:   !GetAtt NetworkStack.Outputs.PrivateDbSubnetIds
        DbSecurityGroupId:    !GetAtt DbStack.Outputs.DbSecurityGroupId
        # Instance/AmiId is left out to use template-defaults

Outputs:
  VpcId:
    Value: !GetAtt NetworkStack.Outputs.VpcId
  PublicSubnetIds:
    Value: !GetAtt NetworkStack.Outputs.PublicSubnetIds
  PrivateAppSubnetIds:
    Value: !GetAtt NetworkStack.Outputs.PrivateAppSubnetIds
  PrivateDbSubnetIds:
    Value: !GetAtt NetworkStack.Outputs.PrivateDbSubnetIds
  AlbDNS:
    Value: !GetAtt AlbStack.Outputs.AlbDNS
    Description: Public DNS för ALB
  AlbArn:
    Value: !GetAtt AlbStack.Outputs.AlbArn
  TargetGroupArn:
    Value: !GetAtt AlbStack.Outputs.TargetGroupArn
  ListenerArn:
    Value: !GetAtt AlbStack.Outputs.ListenerArn
  AlbSecurityGroupId:
    Value: !GetAtt AlbStack.Outputs.AlbSecurityGroupId
  AppSecurityGroupId:
    Value: !GetAtt AsgStack.Outputs.AppSecurityGroupId
    Description: SG-ID för webbinstanser (används av LT/ASG, namnet hintar om det)
  EfsSecurityGroupId:
    Value: !GetAtt EfsStack.Outputs.EfsSecurityGroupId
  DbSecurityGroupId:
    Value: !GetAtt DbStack.Outputs.DbSecurityGroupId
  DbPrivateIp:
    Value: !GetAtt DbEc2Stack.Outputs.DbPrivateIp